layout_spectrum: 0.2686847
typography_spectrum: 0.9177046
color:
  saturation: 0.0655867
  lightness: 0.9487529
  brandStrength: 0.9020305
  rhythmicContrast: 0.3065136
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: OnE Gaming Corner
